name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COREPACK_ENABLE_PREVIEWS: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: false

      - name: Enable Corepack with force
        run: |
          sudo npm install -g corepack
          corepack enable --install-directory=~/bin
          corepack prepare yarn@4.9.1 --activate --force
          echo "~/bin" >> $GITHUB_PATH

      - name: Verify Yarn version
        run: yarn --version

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          yarn set version 4.9.1
          yarn install --immutable

      - name: Build APK
        run: npx eas-cli build --platform android --profile preview --non-interactive --no-wait
